---
name: Lint

on: # yamllint disable-line rule:truthy
  pull_request: null

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v17
      with:
        config: .markdown-lint.yml
        globs: |
          *.md
          !test/*.md
