name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v17
      with:
        config: .markdownlint.json
        globs: |
          *.md
          !test/*.md
